[pytest]
pythonpath = .
testpaths = tests
addopts = -ra
filterwarnings =
    ignore:Using .*starlette\.testclient.*:Warning:fastapi\.testclient
    ignore:Setting the shape on a NumPy array has been deprecated.*:DeprecationWarning